[font]
size = 19
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }

[font.normal]
family = "Lambda"
style = "Regular"

[font.bold]
family = "Lambda"
style = "Bold"

[font.bold_italic]
family = "Lambda"
style = "Bold Italic"

[font.italic]
family = "Lambda"
style = "Italic"

[window]
# opacity = 0.8
dynamic_padding = true
padding = {x = 2, y = 0}
decorations = "None"
option_as_alt = "OnlyLeft"

[mouse]
hide_when_typing = true

[cursor]
style = { shape ="Block", blinking = "Never" }

[keyboard]
bindings = [
  { key = "q", mode = "Vi", action = "ToggleViMode" },
]

[colors.primary]
background = "#211f1c"
foreground = "#adaba5"

[colors]
cursor = { cursor = '#a6e22e' }

[colors.normal]
black = "#646361"
red = "#c37d75"
green = "#7d9663"
yellow = "#ab965d"
blue = "#7c9bbf"
cyan = "#639794"
magenta = "#9f80a4"
white = "#adaba5"

[colors.bright]
yellow = "#ccad52"
