[font]
size = 19
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }

[font.normal]
family = "Lambda"
style = "Regular"

[font.bold]
family = "Lambda"
style = "Bold"

[font.bold_italic]
family = "Lambda"
style = "Bold Italic"

[font.italic]
family = "Lambda"
style = "Italic"

[window]
# opacity = 0.8
dynamic_padding = true
padding = {x = 2, y = 0}
decorations = "None"
option_as_alt = "OnlyLeft"

[mouse]
hide_when_typing = true

[cursor]
style = { shape ="Block", blinking = "Never" }

[keyboard]
bindings = [
  { key = "q", mode = "Vi", action = "ToggleViMode" },
]

[colors.primary]
background = "#1C1C19"
foreground = "#B9BCB6"

[colors]
cursor = { cursor = '#a6e22e' }

[colors.normal]
black = "#586e75"
red = "#B3776F"
green = "#8FAF78"
yellow = "#B59A64"
blue = "#91A7BC"
cyan = "#79AA99"
magenta = "#A98DA6"
white = "#8fa6ab"

[colors.bright]
yellow = "#ccad52"
