[font]
size = 19
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }

[font.normal]
family = "Lambda"
style = "Regular"

[font.bold]
family = "Lambda"
style = "Bold"

[font.bold_italic]
family = "Lambda"
style = "Bold Italic"

[font.italic]
family = "Lambda"
style = "Italic"

[window]
# opacity = 0.8
dynamic_padding = true
padding = {x = 2, y = 0}
decorations = "None"
option_as_alt = "OnlyLeft"

[mouse]
hide_when_typing = true

[cursor]
style = { shape ="Block", blinking = "Never" }

[keyboard]
bindings = [
  { key = "q", mode = "Vi", action = "ToggleViMode" },
]

[colors.primary]
background = "#1b1b15"
foreground = "#bfbeb7"

[colors]
cursor = { cursor = '#a6e22e' }

[colors.normal]
black = "#586e75"
red = "#c8928b"
green = "#8eb890"
yellow = "#c7aa72"
blue = "#89a1bc"
cyan = "#8ab0af"
magenta = "#ae94b1"
white = "#8fa6ab"

[colors.bright]
yellow = "#ccad52"
