[font]
size = 19
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }

[font.normal]
family = "Lambda"
style = "Regular"

[font.bold]
family = "Lambda"
style = "Bold"

[font.bold_italic]
family = "Lambda"
style = "Bold Italic"

[font.italic]
family = "Lambda"
style = "Italic"

[window]
# opacity = 0.8
dynamic_padding = true
padding = {x = 2, y = 0}
decorations = "None"
option_as_alt = "OnlyLeft"

[mouse]
hide_when_typing = true

[cursor]
style = { shape ="Block", blinking = "Never" }

[keyboard]
bindings = [
  { key = "q", mode = "Vi", action = "ToggleViMode" },
]

[colors.primary]
background = "#1b1b1b"
foreground = "#aeaeae"

[colors]
cursor = { cursor = '#a6e22e' }

[colors.normal]
black = "#717171"
red = "#bb7c72"
green = "#6d956f"
yellow = "#9f8a51"
blue = "#758fc1"
cyan = "#6196a0"
magenta = "#a185b6"
white = "#aeaeae"

[colors.bright]
yellow = "#ccad52"
