[font]
size = 19
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }

[font.normal]
family = "Lambda"
style = "Regular"

[font.bold]
family = "Lambda"
style = "Bold"

[font.bold_italic]
family = "Lambda"
style = "Bold Italic"

[font.italic]
family = "Lambda"
style = "Italic"

[window]
# opacity = 0.8
dynamic_padding = true
padding = {x = 2, y = 0}
decorations = "None"
option_as_alt = "OnlyLeft"

[mouse]
hide_when_typing = true

[cursor]
style = { shape ="Block", blinking = "Never" }

[keyboard]
bindings = [
  { key = "q", mode = "Vi", action = "ToggleViMode" },
]

[colors.primary]
background = "#22221c"
foreground = "#b8b8b1"

[colors]
cursor = { cursor = '#a6e22e' }

[colors.normal]
black = "#586e75"
red = "#c3948e"
green = "#84b289"
yellow = "#c6aa70"
blue = "#8b9fbe"
cyan = "#88b1b1"
magenta = "#a995b7"
white = "#8fa6ab"

[colors.bright]
yellow = "#ccad52"
